-- MySQL Script generated by MySQL Workbench
-- Mon May 25 22:57:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDFlorHernan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDFlorHernan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDFlorHernan` DEFAULT CHARACTER SET utf8 ;
USE `BDFlorHernan` ;

-- -----------------------------------------------------
-- Table `BDFlorHernan`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDFlorHernan`.`CATEGORIAS` (
  `cveCategoria` VARCHAR(4) NOT NULL,
  `Tipo` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`cveCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDFlorHernan`.`SUBCATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDFlorHernan`.`SUBCATEGORIAS` (
  `cveSubCategoria` VARCHAR(4) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`cveSubCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDFlorHernan`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDFlorHernan`.`CLIENTES` (
  `Username` VARCHAR(30) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDFlorHernan`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDFlorHernan`.`PRODUCTOS` (
  `Cod_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `cveCategoria` VARCHAR(4) NOT NULL,
  `cveSubCategoria` VARCHAR(4) NOT NULL,
  `Estatus` INT NOT NULL,
  `PrecioUnit` DECIMAL(7,2) NOT NULL,
  `Descripcion` VARCHAR(200) NULL,
  `CATEGORIAS_cveCategoria` VARCHAR(4) NOT NULL,
  `SUBCATEGORIAS_cveSubCategoria` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`Cod_Producto`),
  INDEX `fk_PRODUCTOS_CATEGORIAS1_idx` (`CATEGORIAS_cveCategoria` ASC) ,
  INDEX `fk_PRODUCTOS_SUBCATEGORIAS1_idx` (`SUBCATEGORIAS_cveSubCategoria` ASC) ,
  CONSTRAINT `fk_PRODUCTOS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_cveCategoria`)
    REFERENCES `BDFlorHernan`.`CATEGORIAS` (`cveCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTOS_SUBCATEGORIAS1`
    FOREIGN KEY (`SUBCATEGORIAS_cveSubCategoria`)
    REFERENCES `BDFlorHernan`.`SUBCATEGORIAS` (`cveSubCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDFlorHernan`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDFlorHernan`.`PEDIDOS` (
  `Num_Pedido` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Username` VARCHAR(30) NOT NULL,
  `Cod_Producto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Enviar_Recoge` VARCHAR(35) NOT NULL,
  `Direccion` VARCHAR(55) NOT NULL,
  `Telefono` INT NOT NULL,
  `Fecha_entrega` DATE NOT NULL,
  `Requisitos` VARCHAR(255) NOT NULL,
  `PRODUCTOS_Cod_Producto` INT NOT NULL,
  `CLIENTES_Username` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Num_Pedido`),
  INDEX `fk_PEDIDOS_PRODUCTOS_idx` (`PRODUCTOS_Cod_Producto` ASC),
  INDEX `fk_PEDIDOS_CLIENTES1_idx` (`CLIENTES_Username` ASC),
  CONSTRAINT `fk_PEDIDOS_PRODUCTOS`
    FOREIGN KEY (`PRODUCTOS_Cod_Producto`)
    REFERENCES `BDFlorHernan`.`PRODUCTOS` (`Cod_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDOS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_Username`)
    REFERENCES `BDFlorHernan`.`CLIENTES` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDFlorHernan`.`TICKETS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDFlorHernan`.`TICKETS` (
  `Noº_Ticket` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Num_Pedido` INT NOT NULL,
  `Cod_Producto` INT NOT NULL,
  `PrecioUnit` DECIMAL(7,2) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Importe` DECIMAL(7,2) NOT NULL,
  `Total` DECIMAL(8,2) NOT NULL,
  `PEDIDOS_Num_Pedido` INT NOT NULL,
  PRIMARY KEY (`Noº_Ticket`),
  INDEX `fk_TICKETS_PEDIDOS1_idx` (`PEDIDOS_Num_Pedido` ASC),
  CONSTRAINT `fk_TICKETS_PEDIDOS1`
    FOREIGN KEY (`PEDIDOS_Num_Pedido`)
    REFERENCES `BDFlorHernan`.`PEDIDOS` (`Num_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDFlorHernan`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDFlorHernan`.`VENTAS` (
  `Num_Venta` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Username` VARCHAR(30) NOT NULL,
  `Num_Pedido` INT NOT NULL,
  `Cod_Producto` INT NOT NULL,
  `Noº_Ticket` INT NOT NULL,
  `Total` DECIMAL(8,2) NOT NULL,
  `PEDIDOS_Num_Pedido` INT NOT NULL,
  PRIMARY KEY (`Num_Venta`),
  INDEX `fk_VENTAS_PEDIDOS1_idx` (`PEDIDOS_Num_Pedido` ASC),
  CONSTRAINT `fk_VENTAS_PEDIDOS1`
    FOREIGN KEY (`PEDIDOS_Num_Pedido`)
    REFERENCES `BDFlorHernan`.`PEDIDOS` (`Num_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
